version: "3.7"

services:
  myapp:
    build: .
    restart: always
    ports:
      - "7000:7000"
    depends_on:
      - mongodb
    networks:
      - registration-history-network

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: registry
      MONGO_INITDB_ROOT_PASSWORD: passw0rd
      MONGO_INITDB_DATABASE: registration_history_service
    ports:
      - "27017:27017"
    volumes:
      - ./src/resources/db/V1__create_user.js:/docker-entrypoint-initdb.d/V1__create_user.js:ro
    networks:
      - registration-history-network
    command: ["--bind_ip_all"]

networks:
  registration-history-network:
    driver: bridge
